/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qr_1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class User_managament_module extends javax.swing.JFrame {

    public String role = "NADMIN";

    public User_managament_module() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException {
        initComponents();
        Qr_module n = new Qr_module();
        n.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        n.setVisible(true);
        n.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int showConfirmDialog = JOptionPane.showConfirmDialog(n, "If you close the process will stop");
                if (showConfirmDialog == 0) {
                    n.dispose();
                    dispose();
                    n.close_webcam();
                }
            }
        });
        n.submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTextField1.setText(n.Username());
                jPasswordField1.setText(n.Password_Passer());
                Admin_module ni = new Admin_module();
                File n2 = new File(ni.database_for_User_Database);
                BufferedReader bfr = null;
                try {
                    bfr = new BufferedReader(new FileReader(n2));
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Qr_module.class.getName()).log(Level.SEVERE, null, ex);
                }
                String[] data;
                String str;
                try {
                    while ((str = bfr.readLine()) != null) {
                        data = str.split(",");
                        if (jTextField1.getText().equals(data[0])) {
                            if (new String(jPasswordField1.getPassword()).equals(data[1])) {
                                n.dispose();
                                n.close_webcam();
                            }
                            if (data[5].equals("ADMIN")) {
                                role = "ADMIN";
                            }
                        }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(User_managament_module.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    bfr.close();
                } catch (IOException ex) {
                    Logger.getLogger(User_managament_module.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(994, 399));
        setPreferredSize(new java.awt.Dimension(994, 399));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password Changer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("User Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 90, 97, -1));

        jLabel3.setText("New - Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 124, -1, -1));

        jButton1.setText("Clear");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 208, -1, -1));

        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 208, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 87, 181, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 121, 181, -1));

        jLabel9.setText("Re-enter New - Password :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 152, -1, -1));
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 149, 181, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 177, 130, 25));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 20, 390, 325));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add / RemoveUser", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("User Name :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 43, 106, -1));

        jLabel5.setText("Password :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 68, 106, -1));

        jLabel6.setText("Deposit Amount :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 96, 106, -1));

        jLabel7.setText("Phone Number :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 124, 106, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 246, -1, -1));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 246, -1, -1));

        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.setDoubleBuffered(true);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 194, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 194, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 194, -1));
        jPanel2.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 194, -1));

        jLabel10.setText("Name :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 155, 106, -1));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 194, -1));

        jLabel11.setText("Role :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 184, 43, -1));

        jButton5.setText("To Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 281, -1, -1));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 180, 118, 23));
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 215, 43, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is Your pet Name ?", "What is your 10th Mathametics Standard Teacher Name ?", "Who is your favourite Teacher in sem - 2 ?", " ", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 215, 230, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 190, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER", " " }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 194, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 480, 320));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel8.setText("💖");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 410));

        setSize(new java.awt.Dimension(1045, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField4.setText("");
        jPasswordField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed

    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Please verify your Security Question to Change your password");
        Questionare ni = new Questionare(jTextField1.getText());
        ni.setVisible(true);
        ni.jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == VK_ENTER) {
                    ni.dispose();
                    if (ni.answer.equals(ni.jTextField1.getText())) {
                        JOptionPane.showMessageDialog(rootPane, "Sucess");
                        String path_2 = "C:\\Users\\eshwa\\OneDrive\\Desktop\\Sem-2\\java\\Project\\Pro_temp.csv";
                        BufferedReader file = null;
                        File data = new File("C:\\Users\\eshwa\\OneDrive\\Desktop\\Sem-2\\java\\Project\\Database.csv");
                        JOptionPane.showMessageDialog(rootPane, data);
                        File n1 = new File(path_2);

                        try {
                            file = new BufferedReader(new FileReader(data));
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Remove_Add_cycle.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        BufferedWriter file_temp = null;
                        try {
                            file_temp = new BufferedWriter(new FileWriter(n1));
                        } catch (IOException ex) {
                            Logger.getLogger(Remove_Add_cycle.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        String line;
                        int l2 = 0;
                        boolean present = false;
                        try {
                            while ((line = file.readLine()) != null) {
                                String[] data1 = line.split(",");
                                if (data1[0].equals(jTextField1.getText())) {
                                    l2 = 1;
                                    if (Arrays.toString(jPasswordField2.getPassword()).equals(Arrays.toString(jPasswordField1.getPassword()))) {
                                        present = true;
                                        data1[1] = new String(jPasswordField2.getPassword());
                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "Hey you the password is messed up check it once more");
                                    }
                                }
                                System.out.println(Arrays.toString(data1));
                                file_temp.write(String.join(",", data1));
                                file_temp.newLine();
                            }
                            if (l2 == 0) {
                                jLabel12.setText("There is no such user");
                            }
                        } catch (IOException ex) {
                            Logger.getLogger(Remove_Add_cycle.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        if (present) {
                            JOptionPane.showMessageDialog(rootPane, "Successfully updated the password in the database");
                            try {
                                file.close();
                            } catch (IOException ex) {
                                Logger.getLogger(User_managament_module.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            try {
                                file_temp.close();
                            } catch (IOException ex) {
                                Logger.getLogger(User_managament_module.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            System.out.println(data);
                            System.out.println(data.delete());
                            data.delete();
                            n1.renameTo(data); // Rename the temporary file to the original file name
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "No entry found with the specified model name");
                            n1.delete(); // Delete the temporary file
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Who exactly are you ?");
                }
            }
        }
        );

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            add_user();
        } catch (IOException ex) {
            Logger.getLogger(User_managament_module.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (role.equals("ADMIN")) {
            String path_2 = "C:\\Users\\eshwa\\OneDrive\\Desktop\\Sem-2\\java\\Project\\database_for.csv";
            BufferedReader file = null;
            File data = new File("C:\\Users\\eshwa\\OneDrive\\Desktop\\Sem-2\\java\\Project\\Database.csv");
            JOptionPane.showMessageDialog(rootPane, data);
            JOptionPane.showMessageDialog(rootPane, role);
            File n1 = new File(path_2);

            try {
                file = new BufferedReader(new FileReader(data));
            } catch (FileNotFoundException ex) {
                // Handle file not found exception
            }

            BufferedWriter file_temp = null;
            try {
                file_temp = new BufferedWriter(new FileWriter(n1));

            } catch (IOException ex) {
                Logger.getLogger(Remove_Add_cycle.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            String line;
            String[] data1;
            try {
                boolean removeUser = false; // Flag to determine whether to remove a user

                while ((line = file.readLine()) != null) {
                    data1 = line.split(",");

                    // Check if the current line matches the user to be removed
                    if (jTextField3.getText().equals(data1[0])) {
                        removeUser = true; // Set the flag to remove the user
                        // Skip adding the user to the temporary file
                        continue;
                    }
                    file_temp.write(String.join(",", data1));
                    file_temp.newLine();
                }

                // If removeUser is still false, it means the user was not found in the file
                if (!removeUser) {
                    JOptionPane.showMessageDialog(rootPane, "User not found in the database");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Successfully removed from the database");
                }
            } catch (IOException ex) {
                Logger.getLogger(Remove_Add_cycle.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            try {
                file.close();
                file_temp.close();

            } catch (IOException ex) {
                Logger.getLogger(Remove_Add_cycle.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            data.delete(); // Delete the original file
            n1.renameTo(data);
            System.out.println(n1.renameTo(data));

        } else {
            JOptionPane.showMessageDialog(rootPane, "Wait a minute You Don't have any ADMIN rights");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        int i;
        boolean present = false;
        char inputChar = evt.getKeyChar();

        if (Character.isDigit(inputChar)) {
            for (i = 0; i <= 9; i++) {
                if (i == Character.getNumericValue(inputChar)) {
                    present = true;
                    break;
                }
            }
        }

        if (!present) {
            evt.consume();
        }


    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        int i;
        boolean present = false;
        char inputChar = evt.getKeyChar();

        if (Character.isDigit(inputChar)) {
            for (i = 0; i <= 9; i++) {
                if (i == Character.getNumericValue(inputChar)) {
                    present = true;
                    break;
                }
            }
        }

        if (!present) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_managament_module.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new User_managament_module().setVisible(true);

            } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException ex) {
                Logger.getLogger(User_managament_module.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private boolean check() {
        return !(jTextField3.getText().equals("") || jTextField5.getText().equals("") || jTextField6.getText().equals("") || jTextField7.getText().equals(""));
    }

    public Boolean verify(String user) throws FileNotFoundException, IOException {
        BufferedReader n1;
        n1 = new BufferedReader(new FileReader(new File("C:\\Users\\eshwa\\OneDrive\\Desktop\\Sem-2\\java\\Project\\Database.csv")));
        String line;
        while ((line = n1.readLine()) != null) {
            String[] data = line.split(",");
            if (data[0].equals(user)) {
                return false;
            }
        }
        return true;
    }

    private void add_user() throws IOException {

        if (check()) {
            if (role.equals("ADMIN")) {
                if (verify(jTextField3.getText())) {
                    JOptionPane.showMessageDialog(rootPane, role);
                    Function_add n = new Function_add(String.join(",", jTextField3.getText() + "," + new String(jPasswordField4.getPassword()) + "," + jTextField7.getText() + "," + jTextField6.getText() + "," + jTextField5.getText() + "," + jComboBox2.getSelectedItem() + "," + jComboBox1.getSelectedItem() + "," + jTextField4.getText()));
                    n.add_user();
                    System.out.println(String.join(",", jTextField3.getText() + "," + new String(jPasswordField4.getPassword()) + "," + jTextField7.getText() + "," + jTextField6.getText() + "," + jTextField5.getText() + "," + jComboBox2.getSelectedItem() + "," + jComboBox1.getSelectedItem() + "," + jTextField4.getText()));
                    JOptionPane.showMessageDialog(rootPane, "Successfully Added from the database");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "There is already a person with the same roll no here");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Wait a minute You Don't have any ADMIN rights");
            }
        } else {
            jLabel13.setText("* Please fill out all");
            jLabel13.setForeground(Color.red);
        }
    }
}
